server:
  port: 5001

spring:
  datasource:
    url: jdbc:postgresql://localhost:7000/trader_stage_db
    username: ${username_db}
    password: ${password_db}
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${username_mail}
    password: ${username_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  secret-key: ${secret_key}
  expiration: 900000
  refresh-token-expiration: 604800000
  password-reset-token-expiration: 900000
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173

twitch-api:
  client_id: ${twitch_client_id}
  client_secret: ${twitch_client_secret}
  grant_type: client_credentials
  access_token_base_url: https://id.twitch.tv/oauth2/token