package com.swapper.monolith.ItemService.constants;

import lombok.Getter;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;

@Getter
public enum Platform {
    EPOCH_SUPER_CASSETTE_VISION("Epoch Super Cassette Vision"),
    E_READER_CARD_E_READER("e-Reader / Card-e Reader"),
    XBOX_360("Xbox 360"),
    SEGA_SATURN("Sega Saturn"),
    ATARI_JAGUAR("Atari Jaguar"),
    AY_3_8607("AY-3-8607"),
    TURBOGRAFX_16_PC_ENGINE_CD("Turbografx-16/PC Engine CD"),
    THOMSON_MO5("Thomson MO5"),
    SATELLAVIEW("Satellaview"),
    SEGA_PICO("Sega Pico"),
    AIRCONSOLE("AirConsole"),
    DOS("DOS"),
    ATARI_7800("Atari 7800"),
    WII_U("Wii U"),
    EVERCADE("Evercade"),
    AMSTRAD_GX4000("Amstrad GX4000"),
    MICROCOMPUTER("Microcomputer"),
    ATARI_JAGUAR_CD("Atari Jaguar CD"),
    SEGA_32X("Sega 32X"),
    MSX2("MSX2"),
    ATARI_LYNX("Atari Lynx"),
    SHARP_X1("Sharp X1"),
    NEO_GEO_POCKET_COLOR("Neo Geo Pocket Color"),
    FAIRCHILD_CHANNEL_F("Fairchild Channel F"),
    AMAZON_FIRE_TV("Amazon Fire TV"),
    LEAPSTER_EXPLORER_LEAPPAD_EXPLORER("Leapster Explorer/LeadPad Explorer"),
    AY_3_8500("AY-3-8500"),
    AY_3_8760("AY-3-8760"),
    DRAGON_32_64("Dragon 32/64"),
    PLAYSTATION_5("PlayStation 5"),
    AMSTRAD_PCW("Amstrad PCW"),
    VECTREX("Vectrex"),
    VIRTUAL_BOY("Virtual Boy"),
    AY_3_8603("AY-3-8603"),
    META_QUEST_2("Meta Quest 2"),
    PLAYSTATION_VR2("PlayStation VR2"),
    PANASONIC_JUNGLE("Panasonic Jungle"),
    ATARI_8_BIT("Atari 8-bit"),
    COMMODORE_CDTV("Commodore CDTV"),
    PLAYSTATION_VR("PlayStation VR"),
    UZEBOX("Uzebox"),
    VISUAL_MEMORY_UNIT("Visual Memory Unit / Visual Memory System"),
    ARCADIA_2001("Arcadia 2001"),
    GIZMONDO("Gizmondo"),
    PLAYSTATION_4("PlayStation 4"),
    FAMILY_COMPUTER_DISK_SYSTEM("Family Computer Disk System"),
    MICROVISION("Microvision"),
    COMMODORE_PLUS_4("Commodore Plus/4"),
    WONDERSWAN_COLOR("WonderSwan Color"),
    PC_ENGINE_SUPERGRAFX("PC Engine SuperGrafx"),
    TEXAS_INSTRUMENTS_TI_99("Texas Instruments TI-99"),
    SEGA_CD_32X("Sega CD 32X"),
    LINUX("Linux"),
    PLAYSTATION_2("PlayStation 2"),
    ODYSSEY("Odyssey"),
    PDP_8("PDP-8"),
    DREAMCAST("Dreamcast"),
    NEO_GEO_CD("Neo Geo CD"),
    ACORN_ELECTRON("Acorn Electron"),
    SEGA_GAME_GEAR("Sega Game Gear"),
    IOS("iOS"),
    TAPWAVE_ZODIAC("Tapwave Zodiac"),
    PC_WINDOWS("PC (Microsoft Windows)"),
    SEGA_CD("Sega CD"),
    AY_3_8710("AY-3-8710"),
    AY_3_8605("AY-3-8605"),
    STEAMVR("SteamVR"),
    SINCLAIR_ZX81("Sinclair ZX81"),
    AY_3_8606("AY-3-8606"),
    PC_9800_SERIES("PC-9800 Series"),
    SOL_20("Sol-20"),
    ELEKTOR_TV_GAMES_COMPUTER("Elektor TV Games Computer"),
    GAME_BOY_ADVANCE("Game Boy Advance"),
    PROGRAMMABLE_VIDEO_SYSTEM_1292("1292 Advanced Programmable Video System"),
    FM_7("FM-7"),
    TATUNG_EINSTEIN("Tatung Einstein"),
    NEC_PC_6000_SERIES("NEC PC-6000 Series"),
    GAME_AND_WATCH("Game & Watch"),
    AMIGA_CD32("Amiga CD32"),
    OUYA("Ouya"),
    DONNER_MODEL_30("Donner Model 30"),
    APPLE_IIGS("Apple IIGS"),
    NEO_GEO_POCKET("Neo Geo Pocket"),
    PC_8800_SERIES("PC-8800 Series"),
    ODYSSEY_2_VIDEOPAC_G7000("Odyssey 2 / Videopac G7000"),
    HYPER_NEO_GEO_64("Hyper Neo Geo 64"),
    PC_50X_FAMILY("PC-50X Family"),
    PLAYSTATION_3("PlayStation 3"),
    DEC_GT40("DEC GT40"),
    XBOX("Xbox"),
    IMLAC_PDS_1("Imlac PDS-1"),
    OCULUS_VR("Oculus VR"),
    NINTENDO_DS("Nintendo DS"),
    NINTENDO_ENTERTAINMENT_SYSTEM("Nintendo Entertainment System"),
    PLAYSTATION_VITA("PlayStation Vita"),
    PLAYDIA("Playdia"),
    ACORN_ARCHIMEDES("Acorn Archimedes"),
    PHILIPS_CD_I("Philips CD-i"),
    GAME_BOY_COLOR("Game Boy Color"),
    COMMODORE_C64_128_MAX("Commodore C64/128/MAX"),
    FERRANTI_NIMROD("Ferranti Nimrod Computer"),
    INTELLIVISION("Intellivision"),
    BLACKBERRY_OS("BlackBerry OS"),
    TURBOGRAFX_16_PC_ENGINE("TurboGrafx-16/PC Engine"),
    ATARI_5200("Atari 5200"),
    PDP_11("PDP-11"),
    CDC_CYBER_70("CDC Cyber 70"),
    ONLIVE_GAME_SYSTEM("OnLive Game System"),
    FM_TOWNS("FM Towns"),
    SHARP_X68000("Sharp X68000"),
    SWANCRYSTAL("SwanCrystal"),
    SUPER_NES_CD_ROM_SYSTEM("Super NES CD-ROM System"),
    VC_4000("VC 4000"),
    WINDOWS_MIXED_REALITY("Windows Mixed Reality"),
    SHARP_MZ_2200("Sharp MZ-2200"),
    EPOCH_CASSETTE_VISION("Epoch Cassette Vision"),
    PLUG_AND_PLAY("Plug & Play"),
    GAME_COM("Game.com"),
    PDP_7("PDP-7"),
    INTELLIVISION_AMICO("Intellivision Amico"),
    OCULUS_QUEST("Oculus Quest"),
    OCULUS_RIFT("Oculus Rift"),
    OCULUS_GO("Oculus Go"),
    TEREBIKKO("Terebikko / See 'n Say Video Phone"),
    ADVANCED_PICO_BEENA("Advanced Pico Beena"),
    NINTENDO_SWITCH_2("Nintendo Switch 2"),
    NINTENDO_GAMECUBE("Nintendo GameCube"),
    GAME_BOY("Game Boy"),
    NEW_NINTENDO_3DS("New Nintendo 3DS"),
    N_GAGE("N-Gage"),
    WONDERSWAN("WonderSwan"),
    PLAYSTATION_PORTABLE("PlayStation Portable"),
    BBC_MICROCOMPUTER("BBC Microcomputer System"),
    COMMODORE_VIC_20("Commodore VIC-20"),
    WINDOWS_PHONE("Windows Phone"),
    NEO_GEO_MVS("Neo Geo MVS"),
    NEO_GEO_AES("Neo Geo AES"),
    SG_1000("SG-1000"),
    BALLY_ASTROCADE("Bally Astrocade"),
    COMMODORE_16("Commodore 16"),
    PDP_10("PDP-10"),
    NUON("Nuon"),
    AY_3_8610("AY-3-8610"),
    GOOGLE_STADIA("Google Stadia"),
    GEAR_VR("Gear VR"),
    OOPARTS("OOParts"),
    DAYDREAM("Daydream"),
    CASIO_LOOPY("Casio Loopy"),
    ANALOGUE_ELECTRONICS("Analogue electronics"),
    WATARA_SUPERVISION("Watara/QuickShot Supervision"),
    PANASONIC_M2("Panasonic M2"),
    DIGIBLAST("Digiblast"),
    PLAYDATE("Playdate"),
    POLYMEGA("Polymega"),
    ZX_SPECTRUM("ZX Spectrum"),
    GAMATE("Gamate"),
    MSX("MSX"),
    NINTENDO_3DS("Nintendo 3DS"),
    XBOX_SERIES_X_S("Xbox Series X|S"),
    SEGA_MASTER_SYSTEM("Sega Master System/Mark III"),
    PDP_1("PDP-1"),
    FAMILY_COMPUTER("Family Computer"),
    EDSAC("EDSAC"),
    HP_2100("HP 2100"),
    HP_3000("HP 3000"),
    SDS_SIGMA_7("SDS Sigma 7"),
    CALL_A_COMPUTER("Call-A-Computer time-shared mainframe computer system"),
    PLATO("PLATO"),
    TRS_80_COLOR_COMPUTER("TRS-80 Color Computer"),
    POKEMON_MINI("Pokémon mini"),
    INTERACTIVE_MULTIPLAYER_3DO("3DO Interactive Multiplayer"),
    DVD_PLAYER("DVD Player"),
    BLU_RAY_PLAYER("Blu-ray Player"),
    ZEEBO("Zeebo"),
    PC_FX("PC-FX"),
    HANDHELD_ELECTRONIC_LCD("Handheld Electronic LCD"),
    EXIDY_SORCERER("Exidy Sorcerer"),
    WINDOWS_MOBILE("Windows Mobile"),
    SINCLAIR_QL("Sinclair QL"),
    HYPERSCAN("HyperScan"),
    MEGA_DUCK_COUGAR_BOY("Mega Duck/Cougar Boy"),
    LEGACY_COMPUTER("Legacy Computer"),
    LEAPSTER("Leapster"),
    LEAPTV("LeapTV"),
    PALM_OS("Palm OS"),
    V_SMILE("V.Smile"),
    POCKETSTATION("PocketStation"),
    META_QUEST_3("Meta Quest 3"),
    VISION_OS("visionOS"),
    R_ZONE("R-Zone"),
    APPLE_PIPPIN("Apple Pippin"),
    SUPER_A_CAN("Super A'Can"),
    TOMY_TUTOR("Tomy Tutor / Pyuta / Grandstand Tutor"),
    ANDROID("Android"),
    AMIGA("Amiga"),
    COLECOVISION("ColecoVision"),
    AMSTRAD_CPC("Amstrad CPC"),
    ARCADE("Arcade"),
    SEGA_MEGA_DRIVE_GENESIS("Sega Mega Drive/Genesis"),
    VIRTUAL_CONSOLE("Virtual Console"),
    PLAYSTATION("PlayStation"),
    N64_DD("64DD"),
    ARDUBOY("Arduboy"),
    ATARI_2600("Atari 2600"),
    LEGACY_MOBILE_DEVICE("Legacy Mobile Device"),
    NINTENDO_DSI("Nintendo DSi"),
    COMMODORE_PET("Commodore PET"),
    TRS_80("TRS-80"),
    LASER_ACTIVE("LaserActive"),
    NINTENDO_64("Nintendo 64"),
    WII("Wii"),
    SUPER_NINTENDO_ENTERTAINMENT_SYSTEM("Super Nintendo Entertainment System"),
    XBOX_ONE("Xbox One"),
    SUPER_FAMICOM("Super Famicom"),
    ATARI_ST_STE("Atari ST/STE"),
    APPLE_II("Apple II"),
    MAC("Mac"),
    WEB_BROWSER("Web browser"),
    NINTENDO_SWITCH("Nintendo Switch"),

    UNKOWN("Unknown"),
    ;

    private final String displayName;

    Platform(String displayName) {
        this.displayName = displayName;
    }

    private static final Map<String, Platform> BY_DISPLAY_NAME = Arrays.stream(values())
            .collect(Collectors.toMap(p -> p.displayName.toLowerCase(), p -> p));

    public static Platform fromDisplayName(String name) {
        Platform result = BY_DISPLAY_NAME.get(name.toLowerCase());
        if (result == null) {
            throw new IllegalArgumentException("Unknown platform: " + name);
        }
        return result;
    }

}
